name: project_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.12.0
  flutter_animate: ^1.0.0
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  lottie: ^2.1.0
  confetti: ^0.8.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/piggybank.json
